name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: llama
    provider: ollama
    model: llama3.1:8b
    apiBase: http://<OLLAMA_IP>:11434
    roles:
      - chat
      - edit
      - apply
  - name: Qwen2.5-Coder 1.5B
    provider: ollama
    model: qwen2.5-coder:1.5b-base
    apiBase: http://<OLLAMA_IP>:11434
    roles:
      - autocomplete
  - name: Nomic Embed
    provider: ollama
    model: nomic-embed-text:latest
    apiBase: http://<OLLAMA_IP>:11434
    roles:
      - embed
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
